[package]
name = "bloomware_native"
version = "1.0.0"
authors = ["Rikonardo <me@rikonardo.com>"]
edition = "2021"

[lib]
crate_type = ["cdylib"]

[dependencies]
jni = "0.21.1"
paste = "1.0.14"
gl = "0.14.0"
fontdue = "0.7.3"
once_cell = "1.18.0"